name: flutter_experiment
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  async: ^2.4.2
  http:
  hooks_riverpod:
  flutter_hooks:
  gap:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true