name: flutter_experiment
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  async:
  http:
  hooks_riverpod:
  state_notifier:
  flutter_hooks:
  gap:
  freezed_annotation:
  rxdart:
  functional_widget_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  build_runner: any
  freezed: any
  functional_widget: any
flutter:
  uses-material-design: true